CREATE TABLE IF NOT EXISTS users (
    id         BIGINT UNSIGNED  AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(255)     NOT NULL,
    created_at DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME         NULL
);

CREATE INDEX IF NOT EXISTS idx_users_deleted_at ON users (deleted_at);
